//! The small serializable scene view used by the WebView panels.
//!
//! Kiss3d handles never cross this boundary.  The renderer builds a fresh DTO
//! from its event-loop-owned handles, while this store only keeps Send-safe
//! snapshots and pending edit requests from IPC.

use std::collections::{HashMap, VecDeque};
use std::sync::Mutex;

#[derive(serde::Deserialize, Clone, Debug, PartialEq)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum SceneCommand {
    SetBaseColor { node_id: String, color: [f32; 4] },
    SetMetallic { node_id: String, value: f32 },
    SetRoughness { node_id: String, value: f32 },
    SetVisibility { node_id: String, visible: bool },
}

/// Envelope carried over IPC.  The sequence is generated by the frontend and
/// is monotonic for the lifetime of the page.  It lets the native side discard
/// an older value when delayed invokes arrive out of order.
#[derive(serde::Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SceneCommandEnvelope {
    pub sequence: u64,
    pub command: SceneCommand,
}

impl SceneCommandEnvelope {
    fn key(&self) -> String {
        self.command.key()
    }
}

impl SceneCommand {
    fn key(&self) -> String {
        match self {
            Self::SetBaseColor { node_id, .. } => format!("{node_id}/baseColor"),
            Self::SetMetallic { node_id, .. } => format!("{node_id}/metallic"),
            Self::SetRoughness { node_id, .. } => format!("{node_id}/roughness"),
            Self::SetVisibility { node_id, .. } => format!("{node_id}/visibility"),
        }
    }

    pub(crate) fn property(&self) -> &'static str {
        match self {
            Self::SetBaseColor { .. } => "baseColor",
            Self::SetMetallic { .. } => "metallic",
            Self::SetRoughness { .. } => "roughness",
            Self::SetVisibility { .. } => "visibility",
        }
    }

    pub(crate) fn node_id(&self) -> &str {
        match self {
            Self::SetBaseColor { node_id, .. }
            | Self::SetMetallic { node_id, .. }
            | Self::SetRoughness { node_id, .. }
            | Self::SetVisibility { node_id, .. } => node_id,
        }
    }

    fn validate(&self) -> Result<(), String> {
        let values: &[f32] = match self {
            Self::SetBaseColor { color, .. } => color,
            Self::SetMetallic { value, .. } | Self::SetRoughness { value, .. } => {
                std::slice::from_ref(value)
            }
            Self::SetVisibility { .. } => return Ok(()),
        };
        if values
            .iter()
            .all(|value| value.is_finite() && (0.0..=1.0).contains(value))
        {
            Ok(())
        } else {
            Err("material values must be finite and between 0 and 1".to_string())
        }
    }
}

#[derive(serde::Serialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SceneCommandResult {
    pub sequence: u64,
    pub node_id: String,
    pub property: String,
    pub applied: bool,
    pub error: Option<String>,
}

#[derive(serde::Serialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SceneNodeSummary {
    pub id: String,
    pub parent: Option<String>,
    pub label: String,
    pub kind: String,
    pub visible: bool,
}

#[derive(serde::Serialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SceneTransform {
    pub translation: [f32; 3],
    pub rotation: [f32; 4],
    pub scale: [f32; 3],
}

#[derive(serde::Serialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SceneMaterial {
    pub color: [f32; 4],
    pub metallic: f32,
    pub roughness: f32,
}

#[derive(serde::Serialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SelectedSceneNode {
    pub id: String,
    pub transform: SceneTransform,
    pub material: Option<SceneMaterial>,
}

#[derive(serde::Serialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SceneProjection {
    pub revision: u64,
    pub selected_node_id: Option<String>,
    pub nodes: Vec<SceneNodeSummary>,
    pub selected: Option<SelectedSceneNode>,
    pub last_processed_sequence: u64,
    pub command_results: Vec<SceneCommandResult>,
}

impl Default for SceneProjection {
    fn default() -> Self {
        Self {
            revision: 0,
            selected_node_id: None,
            nodes: Vec::new(),
            selected: None,
            last_processed_sequence: 0,
            command_results: Vec::new(),
        }
    }
}

/// Managed state shared by Tauri commands and the event-loop thread.  Both
/// mutexes contain only owned strings/DTOs, so they are safe to place in
/// `tauri::State`; no `SceneNode3d` or other Kiss3d handle is stored here.
#[derive(Default)]
pub struct SceneProjectionStore {
    projection: Mutex<SceneProjection>,
    pending_selection: Mutex<Option<String>>,
    pending_commands: Mutex<VecDeque<SceneCommandEnvelope>>,
    latest_command_sequences: Mutex<HashMap<String, u64>>,
}

impl SceneProjectionStore {
    pub fn projection(&self) -> SceneProjection {
        self.projection.lock().unwrap().clone()
    }

    pub fn publish(&self, mut projection: SceneProjection) {
        let mut current = self.projection.lock().unwrap();
        projection.revision = current.revision;
        // Renderer snapshots do not own command acknowledgements.  Keep the
        // bounded result history that was recorded by the IPC/event-loop
        // bridge when rebuilding the rest of the projection.
        projection.last_processed_sequence = current.last_processed_sequence;
        projection.command_results = current.command_results.clone();
        if *current == projection {
            return;
        }
        projection.revision = current.revision.saturating_add(1);
        *current = projection;
    }

    pub fn replace_scene(&self, mut projection: SceneProjection) {
        self.pending_selection.lock().unwrap().take();
        self.pending_commands.lock().unwrap().clear();
        self.latest_command_sequences.lock().unwrap().clear();
        let mut current = self.projection.lock().unwrap();
        projection.revision = current.revision.saturating_add(1);
        *current = projection;
    }

    pub fn request_selection(&self, node_id: String) {
        *self.pending_selection.lock().unwrap() = Some(node_id);
    }

    pub fn take_selection(&self) -> Option<String> {
        self.pending_selection.lock().unwrap().take()
    }

    pub fn request_command(&self, envelope: SceneCommandEnvelope) -> Result<(), String> {
        envelope.command.validate()?;
        if envelope.sequence == 0 {
            return Err("command sequence must be greater than zero".to_string());
        }

        let key = envelope.key();
        let mut sequences = self.latest_command_sequences.lock().unwrap();
        let previous = sequences.get(&key).copied().unwrap_or(0);
        if envelope.sequence <= previous {
            drop(sequences);
            self.record_command_result(SceneCommandResult {
                sequence: envelope.sequence,
                node_id: envelope.command.node_id().to_string(),
                property: envelope.command.property().to_string(),
                applied: false,
                error: None,
            });
            return Ok(());
        }
        sequences.insert(key.clone(), envelope.sequence);
        // Coalesce slider/color edits for the same node/property while keeping
        // different properties in the queue.
        let mut pending = self.pending_commands.lock().unwrap();
        if let Some(existing) = pending.iter_mut().find(|item| item.key() == key) {
            if existing.sequence < envelope.sequence {
                *existing = envelope;
            }
        } else {
            pending.push_back(envelope);
        }
        drop(pending);
        drop(sequences);
        Ok(())
    }

    pub fn take_commands(&self) -> Vec<SceneCommandEnvelope> {
        self.pending_commands.lock().unwrap().drain(..).collect()
    }

    pub fn record_command_result(&self, result: SceneCommandResult) {
        let mut projection = self.projection.lock().unwrap();
        projection.last_processed_sequence =
            projection.last_processed_sequence.max(result.sequence);
        projection.command_results.push(result);
        const MAX_RESULTS: usize = 32;
        if projection.command_results.len() > MAX_RESULTS {
            let excess = projection.command_results.len() - MAX_RESULTS;
            projection.command_results.drain(..excess);
        }
        projection.revision = projection.revision.saturating_add(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn store_replaces_pending_selection_and_only_revises_changed_projection() {
        let store = SceneProjectionStore::default();
        store.request_selection("cube".to_string());
        store.request_selection("key-light".to_string());
        assert_eq!(store.take_selection().as_deref(), Some("key-light"));
        assert_eq!(store.take_selection(), None);

        let mut projection = SceneProjection {
            selected_node_id: Some("cube".to_string()),
            ..SceneProjection::default()
        };
        store.publish(projection.clone());
        let first = store.projection();
        store.publish(projection.clone());
        assert_eq!(store.projection().revision, first.revision);

        projection.selected_node_id = Some("key-light".to_string());
        store.publish(projection);
        assert!(store.projection().revision > first.revision);
    }

    #[test]
    fn store_validates_and_preserves_scene_command_order() {
        let store = SceneProjectionStore::default();
        let metallic = SceneCommand::SetMetallic {
            node_id: "cube".to_string(),
            value: 0.75,
        };
        let roughness = SceneCommand::SetRoughness {
            node_id: "cube".to_string(),
            value: 0.25,
        };
        store
            .request_command(SceneCommandEnvelope {
                sequence: 1,
                command: metallic.clone(),
            })
            .unwrap();
        store
            .request_command(SceneCommandEnvelope {
                sequence: 2,
                command: roughness.clone(),
            })
            .unwrap();
        assert_eq!(
            store.take_commands(),
            vec![
                SceneCommandEnvelope {
                    sequence: 1,
                    command: metallic
                },
                SceneCommandEnvelope {
                    sequence: 2,
                    command: roughness
                }
            ]
        );
        assert!(store.take_commands().is_empty());

        assert!(store
            .request_command(SceneCommandEnvelope {
                sequence: 3,
                command: SceneCommand::SetMetallic {
                    node_id: "cube".to_string(),
                    value: f32::NAN,
                },
            })
            .is_err());
        assert!(store
            .request_command(SceneCommandEnvelope {
                sequence: 4,
                command: SceneCommand::SetBaseColor {
                    node_id: "cube".to_string(),
                    color: [1.0, 0.0, 2.0, 1.0],
                },
            })
            .is_err());
    }

    #[test]
    fn stale_same_property_is_rejected_but_different_properties_are_retained() {
        let store = SceneProjectionStore::default();
        let metallic = |sequence, value| SceneCommandEnvelope {
            sequence,
            command: SceneCommand::SetMetallic {
                node_id: "cube".to_string(),
                value,
            },
        };
        let roughness = |sequence, value| SceneCommandEnvelope {
            sequence,
            command: SceneCommand::SetRoughness {
                node_id: "cube".to_string(),
                value,
            },
        };

        store.request_command(metallic(3, 0.8)).unwrap();
        store.request_command(metallic(1, 0.1)).unwrap();
        store.request_command(roughness(2, 0.2)).unwrap();

        let commands = store.take_commands();
        assert_eq!(commands, vec![metallic(3, 0.8), roughness(2, 0.2)]);
        let projection = store.projection();
        assert_eq!(projection.last_processed_sequence, 1);
        assert_eq!(projection.command_results[0].sequence, 1);
        assert!(!projection.command_results[0].applied);
    }

    #[test]
    fn visibility_commands_coalesce_and_reject_stale_sequences() {
        let store = SceneProjectionStore::default();
        let visibility = |sequence, visible| SceneCommandEnvelope {
            sequence,
            command: SceneCommand::SetVisibility {
                node_id: "cube".to_string(),
                visible,
            },
        };

        store.request_command(visibility(9, false)).unwrap();
        store.request_command(visibility(8, true)).unwrap();
        store.request_command(visibility(10, true)).unwrap();

        assert_eq!(store.take_commands(), vec![visibility(10, true)]);
        let projection = store.projection();
        assert_eq!(projection.command_results.len(), 1);
        assert_eq!(projection.command_results[0].property, "visibility");
        assert_eq!(projection.command_results[0].sequence, 8);
        assert!(!projection.command_results[0].applied);
    }

    #[test]
    fn scene_command_deserializes_the_typescript_wire_shape() {
        let command: SceneCommand = serde_json::from_str(
            r#"{"type":"setBaseColor","nodeId":"cube","color":[0.1,0.2,0.3,1.0]}"#,
        )
        .unwrap();
        assert_eq!(
            command,
            SceneCommand::SetBaseColor {
                node_id: "cube".to_string(),
                color: [0.1, 0.2, 0.3, 1.0],
            }
        );

        let visibility: SceneCommand =
            serde_json::from_str(r#"{"type":"setVisibility","nodeId":"cube","visible":false}"#)
                .unwrap();
        assert_eq!(
            visibility,
            SceneCommand::SetVisibility {
                node_id: "cube".to_string(),
                visible: false,
            }
        );
    }

    #[test]
    fn replacing_scene_clears_requests_and_advances_projection_revision() {
        let store = SceneProjectionStore::default();
        store.request_selection("old-node".to_string());
        store
            .request_command(SceneCommandEnvelope {
                sequence: 1,
                command: SceneCommand::SetMetallic {
                    node_id: "cube".to_string(),
                    value: 0.5,
                },
            })
            .unwrap();
        store.replace_scene(SceneProjection {
            selected_node_id: Some("new-node".to_string()),
            ..SceneProjection::default()
        });
        assert_eq!(store.take_selection(), None);
        assert!(store.take_commands().is_empty());
        let projection = store.projection();
        assert_eq!(projection.selected_node_id.as_deref(), Some("new-node"));
        assert_eq!(projection.revision, 1);
    }
}
